name: Deployment

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist


  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Run unit tests
        run: php bin/console test:unit

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy application
        run: |
          ssh 154.56.60.59 "cd var/www/html/korainvest.228lab.com && git pull origin develop"
          ssh 154.56.60.59 "composer install --no-interaction --prefer-dist"
          ssh 154.56.60.59 "php bin/console cache:clear"
          ssh 154.56.60.59 "php bin/console assets:install --symlink"
          ssh 154.56.60.59 "php bin/console doctrine:migrations:migrate --no-interaction"
          ssh 154.56.60.59 "php bin/console server:start"

env:
  DEPLOY_SERVER:  154.56.60.59
  DEPLOY_DIR:  var/www/html/korainvest.228lab.com
